In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ast
from pathlib import Path

In [8]:
base_path = Path(r'C:\Users\Administrator\Desktop\Studies\Python\Python_Project_Hospital_Patient_Record_Analysis\0_Dataset\0_raw')

data_dictionary = pd.read_csv(base_path / 'data_dictionary.csv')
df_encounters = pd.read_csv(base_path / 'encounters.csv')
df_organizations = pd.read_csv(base_path / 'organizations.csv')
df_patients = pd.read_csv(base_path / 'patients.csv')
df_payers = pd.read_csv(base_path / 'payers.csv')
df_procedures = pd.read_csv(base_path / 'procedures.csv')

In [3]:
data_dictionary[data_dictionary['Table'] == 'patients'][['Field','Description']]

               Field                                        Description
24               NaN                          Patient demographic data.
25                Id     Primary Key. Unique Identifier of the patient.
26         BirthDate        The date (YYYY-MM-DD) the patient was born.
27         DeathDate            The date (YYYY-MM-DD) the patient died.
28            Prefix          Name prefix, such as Mr., Mrs., Dr., etc.
29             First                         First name of the patient.
30            Middle                        Middle name of the patient.
31              Last                    Last or surname of the patient.
32            Suffix             Name suffix, such as PhD, MD, JD, etc.
33            Maiden                        Maiden name of the patient.
34           Marital  Marital Status. M is married, S is single. Cur...
35              Race         Description of the patient's primary race.
36         Ethnicity    Description of the patient's primary ethnicity.
37            Gender                    Gender. M is male, F is female.
38        BirthPlace       Name of the town where the patient was born.
39           Address  Patient's street address without commas or new...
40              City                            Patient's address city.
41             State                           Patient's address state.
42            County                          Patient's address county.
43  FIPS County Code                        Patient's FIPS county code.
44               Zip                                Patient's zip code.
45               Lat                     Latitude of Patient's address.
46               Lon                    Longitude of Patient's address.

In [4]:
df_patients.head(5)

,Id,BIRTHDATE,DEATHDATE,PREFIX,FIRST,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON
0,5605b66b-e92d-c16c-1b83-b8bf7040d51f,1977-03-19,NaN,Mrs.,Nikita578,Erdman779,NaN,Leannon79,M,white,nonhispanic,F,Wakefield Massachusetts US,510 Little Station Unit 69,Quincy,Massachusetts,Norfolk County,2186.0,42.290937,-70.975503
1,6e5ae27c-8038-7988-e2c0-25a103f01bfa,1940-02-19,NaN,Mr.,Zane918,Hodkiewicz467,NaN,NaN,M,white,nonhispanic,M,Brookline Massachusetts US,747 Conn Throughway,Boston,Massachusetts,Suffolk County,2135.0,42.308831,-71.063162
2,8123d076-0886-9007-e956-d5864aa121a7,1958-06-04,NaN,Mr.,Quinn173,Marquardt819,NaN,NaN,M,white,nonhispanic,M,Gardner Massachusetts US,816 Okuneva Extension Apt 91,Quincy,Massachusetts,Norfolk County,2170.0,42.265177,-70.967085
3,770518e4-6133-648e-60c9-071eb2f0e2ce,1928-12-25,2017-09-29,Mr.,Abel832,Smitham825,NaN,NaN,M,white,hispanic,M,Randolph Massachusetts US,127 Cole Way Unit 95,Boston,Massachusetts,Suffolk County,2118.0,42.334304,-71.066801
4,f96addf5-81b9-0aab-7855-d208d3d352c5,1928-12-25,2014-02-23,Mr.,Edwin773,Labadie908,NaN,NaN,M,white,hispanic,M,Stow Massachusetts US,976 Ziemann Gateway,Boston,Massachusetts,Suffolk County,2125.0,42.346771,-71.058813

In [5]:
df_patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          974 non-null    object
 1   BIRTHDATE   974 non-null    object
 2   DEATHDATE   154 non-null    object
 3   PREFIX      974 non-null    object
 4   FIRST       974 non-null    object
 5   LAST        974 non-null    object
 6   SUFFIX      21 non-null     object
 7   MAIDEN      386 non-null    object
 8   MARITAL     973 non-null    object
 9   RACE        974 non-null    object
 10  ETHNICITY   974 non-null    object
 11  GENDER      974 non-null    object
 12  BIRTHPLACE  974 non-null    object
 13  ADDRESS     974 non-null    object
 14  CITY        974 non-null    object
 15  STATE       974 non-null    object
 16  COUNTY      974 non-null    object
 17  ZIP         832 non-null    float64
 18  LAT         974 non-null    float64
 19  LON         974 non-null    float64
dtypes: float64(3), object(17)
memory usage: 152.3+ KB

In [14]:
df_patients['BIRTHDATE'] = pd.to_datetime(df_patients['BIRTHDATE'])
df_patients['DEATHDATE'] = pd.to_datetime(df_patients['DEATHDATE'])

def cleaned(text):
    if pd.notna(text):
        return "".join(c for c in text if not(c.isdigit()))
    else: 
        return np.nan

df_patients['FIRST'] = df_patients['FIRST'].apply(cleaned)
df_patients['LAST'] = df_patients['LAST'].apply(cleaned)
df_patients['MAIDEN'] = df_patients['MAIDEN'].apply(cleaned)

df_patients

,Id,BIRTHDATE,DEATHDATE,PREFIX,FIRST,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON
0,5605b66b-e92d-c16c-1b83-b8bf7040d51f,1977-03-19,NaT,Mrs.,Nikita,Erdman,NaN,Leannon,M,white,nonhispanic,F,Wakefield Massachusetts US,510 Little Station Unit 69,Quincy,Massachusetts,Norfolk County,2186.0,42.290937,-70.975503
1,6e5ae27c-8038-7988-e2c0-25a103f01bfa,1940-02-19,NaT,Mr.,Zane,Hodkiewicz,NaN,NaN,M,white,nonhispanic,M,Brookline Massachusetts US,747 Conn Throughway,Boston,Massachusetts,Suffolk County,2135.0,42.308831,-71.063162
2,8123d076-0886-9007-e956-d5864aa121a7,1958-06-04,NaT,Mr.,Quinn,Marquardt,NaN,NaN,M,white,nonhispanic,M,Gardner Massachusetts US,816 Okuneva Extension Apt 91,Quincy,Massachusetts,Norfolk County,2170.0,42.265177,-70.967085
3,770518e4-6133-648e-60c9-071eb2f0e2ce,1928-12-25,2017-09-29,Mr.,Abel,Smitham,NaN,NaN,M,white,hispanic,M,Randolph Massachusetts US,127 Cole Way Unit 95,Boston,Massachusetts,Suffolk County,2118.0,42.334304,-71.066801
4,f96addf5-81b9-0aab-7855-d208d3d352c5,1928-12-25,2014-02-23,Mr.,Edwin,Labadie,NaN,NaN,M,white,hispanic,M,Stow Massachusetts US,976 Ziemann Gateway,Boston,Massachusetts,Suffolk County,2125.0,42.346771,-71.058813
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,d684571e-a784-ef61-429e-06fa0d2b1637,1924-03-15,NaT,Mr.,Chris,Fisher,NaN,NaN,S,white,nonhispanic,M,Franklin Massachusetts US,810 Yundt Forge Suite 2,Medford,Massachusetts,Middlesex County,2145.0,42.357626,-71.040837
970,13c6f26e-17b7-f534-04db-78a26b26018d,1940-10-31,NaT,Mrs.,Berneice,Heaney,NaN,Hermiston,M,white,nonhispanic,F,Templeton Massachusetts US,617 MacGyver Pathway,Boston,Massachusetts,Suffolk County,2152.0,42.331490,-71.039520
971,521e998b-ff0e-767f-b0ee-2bdf1168d66c,1943-04-18,NaT,Mr.,Jamal,VonRueden,NaN,NaN,M,white,nonhispanic,M,Chelmsford Massachusetts US,505 Mertz Path Apt 40,Boston,Massachusetts,Suffolk County,2134.0,42.341971,-71.040624
972,b57e24a2-2e48-12f9-3293-c88745cfdc3f,1941-04-28,NaT,Mrs.,Chrissy,Rempel,NaN,Beer,M,asian,nonhispanic,F,Needham Massachusetts US,366 Beer Crossroad,Cambridge,Massachusetts,Middlesex County,NaN,42.337040,-71.094676
973,204f8028-72f8-d6f8-761f-79ebf9f02311,1923-02-14,NaT,Mrs.,Melaine,Hintz,NaN,Baumbach,M,white,nonhispanic,F,Southwick Massachusetts US,382 Mosciski Road,Boston,Massachusetts,Suffolk County,2128.0,42.357333,-71.057372